myapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.MyAppIndex, name='MyAppIndex')
]

todo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^myapp/', include('myapp.urls', namespace='myapp')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models


class TodoBord(models.Model):
    new_message = models.CharField(max_length=200,)
    image_url = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import TodoBord


def MyAppIndex(request):
    msg = request.GET.get('words')

    delete_text = request.POST.getlist('delete_text')

    if delete_text:
        TodoBord.objects.all().delete()

    data_list = TodoBord.objects.order_by('-id')
    contexts = {
        'result_list': data_list
    }

    if msg is not None:
        message_data = TodoBord()
        message_data.new_message = msg
        message_data.image_url = request.FILES.get('files')
        message_data.save()

    return render(request, 'myapp/index.html', contexts)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
    <title>Title</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body %}
<form action="{% url 'myapp:MyAppIndex' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>message : <input type="file" size="20" name="files" /></label>
    <label>message : <input type="text" size="20" name="words" /></label>
    <input type="submit" value="send" />
</form>

    <form action="{% url 'myapp:MyAppIndex' %}" method="post">
        {% csrf_token %}
        {% include "myapp/result.html" %}
        <input type="submit" value="delete"/>
    </form>

{% endblock %}

myapp/templates/myapp/result.html
{%  block body %}
{% if result_list %}
{% for i in result_list %}
    <p><img src="{{ i.image_url.url }}" /></p>
    <p>
        <input type="checkbox" name="delete_text" value="{{ i.id }}">
        {{ i.new_message }} :{{ i.created_at }}
    </p>
{% endfor %}
{% endif %}
{% endblock %}